### ISSUE TITLE
Unraid FSM image has extra whitespace character at the end of 'FACTORIO_VERSION' environment variable

### ISSUE THREAD

**Issue by sainsley1** [lordfiSh/unraid-docker-images#3]
The Unraid FSM image contains the environment variable 'FACTORIO_VERSION' to control which version of Factorio is installed.
However, currently the Unraid FSM image automatically installs the latest experimental version, even when this environment variable is set to 'stable' (as it is by default). This is because the environment variable is actually created as 'FACTORIO_VERSION ', with a single whitespace character at the end. I have verified this through removing/readding the container a few times and each time the variable is recreated the same way. I removed the offending whitespace character and now my server downloads the correct stable version. 

Steps to reproduce:

    Deploy FactorioServerManager container via the Unraid 'Apps' from lordfiSh's repository using all default settings
    Edit the newly created FactorioServerManager container
    Observe that the Environment Variable 'FACTORIO_VERSION' contains an extra space at the end, and that the Container has, by default, been installed on the latest experimental version as opposed to the latest stable version, despite the 'FACTORIO_VERSION ' environment variable being set to 'stable' by default

![303459714-440744c4-3c63-41a5-861b-788e5092357b](https://github.com/lordfiSh/unraid-docker-images/assets/159409788/dda094ef-b8e4-4d7d-aedc-d1732f863169)
Note how you can see my cursor in the 'FACTORIO_VERSION ' section. This is illustrating the extra whitespace which is causing the problem.
If you remove this single whitespace character and restart the server, the Factorio version will now change from Experimental latest, to Stable latest.

**Comment by lordfiSh** [comment]
Thanks
